CREATE TABLE IF NOT EXISTS `analytics_events` (
	`id` bigint AUTO_INCREMENT NOT NULL,
	`event_id` varchar(64) NOT NULL,
	`event_type` varchar(32) NOT NULL DEFAULT 'page_view',
	`occurred_at` datetime(6) NOT NULL,
	`session_key` varchar(128) NOT NULL,
	`visitor_key` varchar(128) NOT NULL,
	`path` varchar(500) NOT NULL,
	`locale_code` varchar(20),
	`referrer_domain` varchar(512),
	`utm_source` varchar(256),
	`utm_medium` varchar(256),
	`utm_campaign` varchar(256),
	`device_type` varchar(32),
	`browser` varchar(64),
	`operating_system` varchar(64),
	`viewport_bucket` varchar(32),
	`is_bot` boolean NOT NULL DEFAULT false,
	`created_at` datetime(6) NOT NULL,
	CONSTRAINT `analytics_events_id` PRIMARY KEY(`id`),
	CONSTRAINT `analytics_events_event_id_key` UNIQUE(`event_id`),
	KEY `analytics_events_session_idx` (`session_key`,`occurred_at`),
	KEY `analytics_events_visitor_idx` (`visitor_key`,`occurred_at`),
	KEY `analytics_events_path_idx` (`path`,`occurred_at`),
	KEY `analytics_events_occurred_idx` (`occurred_at`)
);--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `analytics_sessions` (
	`id` bigint AUTO_INCREMENT NOT NULL,
	`session_key` varchar(128) NOT NULL,
	`visitor_key` varchar(128) NOT NULL,
	`started_at` datetime(6) NOT NULL,
	`last_seen_at` datetime(6) NOT NULL,
	`landing_path` varchar(2048) NOT NULL,
	`exit_path` varchar(2048),
	`source` varchar(128) NOT NULL DEFAULT 'direct',
	`medium` varchar(128),
	`campaign` varchar(256),
	`locale_code` varchar(20),
	`device_type` varchar(32),
	`browser` varchar(64),
	`operating_system` varchar(64),
	`pageviews` int NOT NULL DEFAULT 0,
	`is_bounce` boolean NOT NULL DEFAULT true,
	`is_bot` boolean NOT NULL DEFAULT false,
	`created_at` datetime(6) NOT NULL,
	`updated_at` datetime(6) NOT NULL,
	CONSTRAINT `analytics_sessions_id` PRIMARY KEY(`id`),
	CONSTRAINT `analytics_sessions_session_key_key` UNIQUE(`session_key`),
	KEY `analytics_sessions_visitor_idx` (`visitor_key`),
	KEY `analytics_sessions_started_idx` (`started_at`)
);
