import {
  ActivityIcon,
  BadgeCheckIcon,
  BellIcon,
  BoxIcon,
  CircleIcon,
  ClipboardListIcon,
  CreditCardIcon,
  FileTextIcon,
  FilesIcon,
  GlobeIcon,
  HistoryIcon,
  ClockIcon,
  ImageIcon,
  KeyRoundIcon,
  LayoutDashboardIcon,
  MenuIcon,
  PackageIcon,
  PencilIcon,
  PlusIcon,
  SettingsIcon,
  ShieldIcon,
  ShoppingCartIcon,
  SparklesIcon,
  StarIcon,
  TagIcon,
  Trash2Icon,
  UserIcon,
  UserRoundIcon,
  UsersIcon,
  EyeIcon
} from 'lucide-vue-next'
import type { Component } from 'vue'

const map: Record<string, Component> = {
  'activity': ActivityIcon,
  'badge-check': BadgeCheckIcon,
  'bell': BellIcon,
  'box': BoxIcon,
  'circle': CircleIcon,
  'clipboard': ClipboardListIcon,
  'credit-card': CreditCardIcon,
  'dashboard': LayoutDashboardIcon,
  'eye': EyeIcon,
  'file-text': FileTextIcon,
  'files': FilesIcon,
  'history': HistoryIcon,
  'clock': ClockIcon,
  'globe': GlobeIcon,
  'image': ImageIcon,
  'key': KeyRoundIcon,
  'menu': MenuIcon,
  'package': PackageIcon,
  'pencil': PencilIcon,
  'plus': PlusIcon,
  'settings': SettingsIcon,
  'shield': ShieldIcon,
  'shopping-cart': ShoppingCartIcon,
  'sparkles': SparklesIcon,
  'star': StarIcon,
  'tag': TagIcon,
  'trash': Trash2Icon,
  'user': UserIcon,
  'user-round': UserRoundIcon,
  'users': UsersIcon
}

/** resolve a lucide icon by framework key; falls back to a plain circle */
export function getIcon(name?: string): Component {
  return (name && map[name]) || CircleIcon
}
