create table if not exists public.comments (id bigint generated by default as identity primary key, post_id bigint not null references public.posts(id) on delete cascade, parent_id bigint references public.comments(id) on delete cascade, user_id bigint references public.users(id) on delete set null, author_name varchar(80) not null, author_email varchar(255) not null, content text not null, status varchar(20) not null default 'pending', created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create index if not exists comments_post_status_idx on public.comments(post_id, status);
create index if not exists comments_parent_idx on public.comments(parent_id);
create index if not exists comments_user_idx on public.comments(user_id);
alter table public.comments enable row level security;
revoke all on table public.comments from anon, authenticated;
