alter table if exists public.users add column if not exists role varchar(20) not null default 'viewer';
alter table if exists public.users add column if not exists status varchar(20) not null default 'active';

create table if not exists public.author_social_channels (
  id bigint generated by default as identity primary key,
  platform varchar(30) not null,
  url varchar(500) not null,
  handle varchar(120) not null default '',
  description varchar(300) not null default '',
  show_in_sidebar boolean not null default true,
  show_in_hero boolean not null default true,
  show_in_social boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);
create table if not exists public.author_page_sections (
  id bigint generated by default as identity primary key,
  type varchar(40) not null unique,
  enabled boolean not null default true,
  sort_order integer not null default 0,
  config jsonb
);
create table if not exists public.author_experiences (
  id bigint generated by default as identity primary key,
  role varchar(120) not null,
  organization varchar(120) not null default '',
  period varchar(60) not null default '',
  current boolean not null default false,
  location varchar(120) not null default '',
  description text,
  url varchar(500),
  sort_order integer not null default 0
);
create table if not exists public.author_projects (
  id bigint generated by default as identity primary key,
  name varchar(120) not null,
  description text,
  image_media_id bigint,
  url varchar(500),
  github_url varchar(500),
  tags varchar(300) not null default '',
  featured boolean not null default false,
  sort_order integer not null default 0
);
create table if not exists public.author_skills (
  id bigint generated by default as identity primary key,
  group_name varchar(60) not null default '',
  name varchar(80) not null,
  sort_order integer not null default 0
);
create table if not exists public.author_education (
  id bigint generated by default as identity primary key,
  school varchar(120) not null,
  program varchar(120) not null default '',
  period varchar(60) not null default '',
  details varchar(500) not null default '',
  sort_order integer not null default 0
);
create table if not exists public.author_certifications (
  id bigint generated by default as identity primary key,
  name varchar(120) not null,
  issuer varchar(120) not null default '',
  date_issued varchar(40) not null default '',
  url varchar(500),
  sort_order integer not null default 0
);
create table if not exists public.author_focus_items (
  id bigint generated by default as identity primary key,
  text varchar(200) not null,
  sort_order integer not null default 0
);

do $$ declare t text; begin
  foreach t in array array['author_social_channels','author_page_sections','author_experiences','author_projects','author_skills','author_education','author_certifications','author_focus_items'] loop
    execute format('alter table public.%I enable row level security', t);
    execute format('revoke all on table public.%I from anon, authenticated', t);
  end loop;
end $$;
