create table if not exists public.sessions (
  id bigint generated by default as identity primary key,
  token_hash varchar(64) not null unique,
  user_id bigint not null references public.users(id) on delete cascade,
  expires_at timestamptz not null,
  created_at timestamptz not null default now()
);
create index if not exists sessions_user_idx on public.sessions(user_id);
create index if not exists sessions_expires_idx on public.sessions(expires_at);

create table if not exists public.password_reset_tokens (
  id bigint generated by default as identity primary key,
  token_hash varchar(64) not null unique,
  user_id bigint not null references public.users(id) on delete cascade,
  expires_at timestamptz not null,
  used_at timestamptz,
  created_at timestamptz not null default now()
);
create index if not exists password_reset_tokens_user_idx on public.password_reset_tokens(user_id);

alter table public.sessions enable row level security;
alter table public.password_reset_tokens enable row level security;
revoke all on table public.sessions from anon, authenticated;
revoke all on table public.password_reset_tokens from anon, authenticated;
