-- Domain core baseline for PostgreSQL/Supabase.
-- This migration is additive: it does not drop or rewrite legacy MySQL data.
create table if not exists public.locales (
  id bigint generated by default as identity primary key,
  code varchar(20) not null unique,
  name varchar(80) not null,
  native_name varchar(80) not null,
  url_prefix varchar(20) unique,
  enabled boolean not null default true,
  content_enabled boolean not null default false,
  ui_enabled boolean not null default false,
  is_default boolean not null default false,
  fallback_locale_id bigint references public.locales(id) on delete set null,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create unique index if not exists locales_one_default_idx on public.locales (is_default) where is_default;

create table if not exists public.users (
  id bigint generated by default as identity primary key,
  name varchar(120) not null,
  email varchar(255) not null unique,
  password_hash varchar(255) not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.pages (
  id bigint generated by default as identity primary key,
  alias varchar(120) not null unique,
  primary_locale_id bigint not null references public.locales(id),
  author_id bigint not null references public.users(id),
  template varchar(40) not null default 'default',
  status varchar(20) not null default 'draft',
  published_at timestamptz,
  deleted_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists pages_status_idx on public.pages(status);

create table if not exists public.page_translations (
  id bigint generated by default as identity primary key,
  page_id bigint not null references public.pages(id) on delete cascade,
  locale_id bigint not null references public.locales(id) on delete cascade,
  title varchar(255) not null,
  content text not null,
  seo_title varchar(255) not null default '',
  seo_description varchar(500) not null default '',
  canonical_url varchar(500),
  noindex boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(page_id, locale_id)
);

create table if not exists public.posts (
  id bigint generated by default as identity primary key,
  alias varchar(120) not null unique,
  primary_locale_id bigint not null references public.locales(id),
  author_id bigint not null references public.users(id),
  featured_media_id bigint,
  access_type varchar(20) not null default 'public',
  paid_price_minor bigint,
  paid_currency varchar(3),
  status varchar(20) not null default 'draft',
  published_at timestamptz,
  scheduled_at timestamptz,
  comment_status varchar(20) not null default 'closed',
  deleted_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists posts_status_idx on public.posts(status);
create index if not exists posts_published_at_idx on public.posts(published_at);

create table if not exists public.post_translations (
  id bigint generated by default as identity primary key,
  post_id bigint not null references public.posts(id) on delete cascade,
  locale_id bigint not null references public.locales(id) on delete cascade,
  title varchar(255) not null,
  excerpt varchar(500) not null default '',
  content text not null,
  seo_title varchar(255) not null default '',
  seo_description varchar(500) not null default '',
  canonical_url varchar(500),
  noindex boolean not null default false,
  featured_image_id bigint,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(post_id, locale_id)
);
create index if not exists post_translations_locale_idx on public.post_translations(locale_id);

create table if not exists public.author_profile (
  id bigint generated by default as identity primary key,
  avatar_media_id bigint,
  hero_config jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create table if not exists public.author_profile_translations (
  id bigint generated by default as identity primary key,
  profile_id bigint not null references public.author_profile(id) on delete cascade,
  locale_id bigint not null references public.locales(id) on delete cascade,
  display_name varchar(80) not null,
  headline varchar(120) not null default '',
  bio text,
  location varchar(120) not null default '',
  updated_at timestamptz not null default now(),
  unique(profile_id, locale_id)
);

create table if not exists public.url_redirects (
  id bigint generated by default as identity primary key,
  entity_type varchar(20) not null,
  entity_id bigint not null,
  locale_id bigint references public.locales(id) on delete set null,
  old_path varchar(500) not null unique,
  new_path varchar(500) not null,
  status_code integer not null default 301 check (status_code in (301, 308)),
  created_at timestamptz not null default now(),
  expires_at timestamptz
);
create index if not exists url_redirects_old_path_idx on public.url_redirects(old_path);

create table if not exists public.settings (
  id bigint generated by default as identity primary key,
  key varchar(80) not null unique,
  value text not null,
  type varchar(20) not null default 'string',
  "group" varchar(40) not null default 'General',
  is_public boolean not null default false,
  description varchar(255),
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create table if not exists public.localized_settings (
  id bigint generated by default as identity primary key,
  key varchar(80) not null,
  locale_id bigint not null references public.locales(id) on delete cascade,
  value text not null,
  updated_at timestamptz not null default now(),
  unique(key, locale_id)
);

-- These are server-owned tables. Keep them inaccessible through the Data API;
-- the backend uses the PostgreSQL connection pool and applies authorization.
do $$ declare t text; begin
  foreach t in array array['locales','users','pages','page_translations','posts','post_translations','author_profile','author_profile_translations','url_redirects','settings','localized_settings'] loop
    execute format('alter table public.%I enable row level security', t);
    execute format('revoke all on table public.%I from anon, authenticated', t);
  end loop;
end $$;
